In [1]:
import subprocess
from SDDS import readSDDS
from conversions import convert_units_elegant2olive, convert_units_olive2elegant

In [2]:
# Run Elegant
subprocess.call("cd test_data/ && elegant elegant_run.ele", shell=True)  # Returns 0 on sucess

0

# Working SDDS Files


In [2]:
# Instantiate read objects for bunch input and ouput SDDS files
in_sdds_file = readSDDS("test_data/elegant_run.bun", verbose=True)
out_sdds_file = readSDDS("test_data/elegant_run.out", verbose=True)

In [3]:
in_particle_data = in_sdds_file.read_columns()

passed
Parameter unpack size: 32 bytes 
Column unpack size: 52 bytes
Parameter key string: =iiddii 
Column key string: =ddddddi
Header data read and parsed.


In [4]:
out_particle_data = out_sdds_file.read_columns()

passed
Parameter unpack size: 32 bytes 
Column unpack size: 52 bytes
Parameter key string: =iiddii 
Column key string: =ddddddi
Header data read and parsed.


In [5]:
out_sdds_file.read_params()

OrderedDict([('rowCount', 10),
             ('Step', 1),
             ('pCentral', 264.1883529100817),
             ('Charge', 1.35e-10),
             ('Particles', 10),
             ('IDSlotsPerBunch', 10)])

In [6]:
# Check if arrays match exactly simulation is a zero-length drift so coordinates should not change between in and out
np.array_equal(in_particle_data, out_particle_data)

True

In [7]:
# Convert elegant units to Olive
olive_out_conversion = convert_units_elegant2olive(out_particle_data)

In [8]:
# Visual double check of longitudinal coordinates
olive_out_conversion[:,4]*1e-2

array([ -9.83700252e-04,  -1.71709903e-03,  -1.28316925e-03,
         1.58820167e-03,  -6.16746179e-05,   6.96107670e-04,
        -3.88351988e-04,  -7.01839410e-04,   1.18372106e-03,
         1.66780414e-03])

In [13]:
# Convert Olive units back to Elegant
olive_back2_elegant = convert_units_olive2elegant(olive_out_conversion[:,0], olive_out_conversion[:,1],
                                                 olive_out_conversion[:,2], olive_out_conversion[:,3],
                                                 olive_out_conversion[:,4], olive_out_conversion[:,5])

(10, 6)
[ 0.99999283  0.99999282  0.99999284  0.99999282  0.99999283  0.99999283
  0.99999285  0.99999285  0.99999286  0.99999283]


In [14]:
# Visual double check
olive_back2_elegant

array([[ -2.14048958e-04,  -3.40846660e-05,   1.04426848e-04,
          3.87973685e-06,   3.28129437e-12,   2.64063485e+02],
       [  1.07463525e-05,   1.38243793e-05,  -2.05163954e-04,
          1.18980670e-05,   5.72766695e-12,   2.63970421e+02],
       [ -9.21835568e-05,   4.68808654e-08,  -3.80258229e-05,
         -1.20649942e-05,   4.28022255e-12,   2.64195371e+02],
       [ -6.38821081e-05,   3.55045566e-05,   8.54601205e-05,
         -6.80448017e-06,  -5.29770856e-12,   2.63958250e+02],
       [ -3.45842410e-05,   2.50543336e-06,  -5.61945933e-05,
         -4.01077291e-05,   2.05725856e-13,   2.64138104e+02],
       [  1.26946318e-04,  -3.09601694e-05,   1.51680382e-04,
          4.06903247e-05,  -2.32198189e-12,   2.64151992e+02],
       [  6.55456843e-05,  -2.27123426e-05,  -3.24155977e-05,
          1.65719283e-05,   1.29541206e-12,   2.64448920e+02],
       [  8.44385451e-05,   3.21726168e-05,   1.45089784e-04,
         -3.03325218e-05,   2.34110102e-12,   2.64384111e+02],


In [15]:
# Check that output data from elegant matches the elegant-to-olive-to-elegant data
# Matches to within 1e-5 precision if element is True
for i in range(6):
    print np.isclose(out_particle_data[:,i], olive_back2_elegant[:,i])

[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]


# Testing Import of Previously Broken Files

In [122]:
wp_file = readSDDS("test_data/bunch.wp", verbose=True)

In [130]:
wp_par = wp_file.read_params()

In [131]:
# Parameters are read in but s is incorrect, should be s=0.0
wp_file.parameters

{'Charge': 1.35e-10,
 'Description': '',
 'ElapsedCoreTime': 0.0,
 'ElapsedTime': 0.0,
 'IDSlotsPerBunch': 10,
 'MemoryUsage': 0,
 'Particles': 10,
 'Pass': 0,
 'PassCentralTime': 0.0,
 'PassLength': 0.0,
 'PreviousElementName': 'D1',
 'SVNVersion': '22803M',
 'Step': 2.0,
 'pCentral': 264.1883529100817,
 'rowCount': 10,
 's': 0.0}

In [128]:
wp_col = wp_file.read_columns()

In [129]:
wp_col

array([[ -2.14048958e-04,  -3.40846660e-05,   1.04426848e-04,
          3.87973685e-06,   3.28129437e-12,   2.64063485e+02,
          3.28129437e-12,   1.00000000e+00],
       [  1.07463525e-05,   1.38243793e-05,  -2.05163954e-04,
          1.18980670e-05,   5.72766695e-12,   2.63970421e+02,
          5.72766695e-12,   2.00000000e+00],
       [ -9.21835568e-05,   4.68808654e-08,  -3.80258229e-05,
         -1.20649942e-05,   4.28022255e-12,   2.64195371e+02,
          4.28022255e-12,   3.00000000e+00],
       [ -6.38821081e-05,   3.55045566e-05,   8.54601205e-05,
         -6.80448017e-06,  -5.29770856e-12,   2.63958250e+02,
         -5.29770856e-12,   4.00000000e+00],
       [ -3.45842410e-05,   2.50543336e-06,  -5.61945933e-05,
         -4.01077291e-05,   2.05725856e-13,   2.64138104e+02,
          2.05725856e-13,   5.00000000e+00],
       [  1.26946318e-04,  -3.09601694e-05,   1.51680382e-04,
          4.06903247e-05,  -2.32198189e-12,   2.64151992e+02,
         -2.32198189e-12,   6.0

# Write out bunch to SDDS 

Bunch taken from elegant, converted to Olive units, converted back to elegant units, written to sdds_beam compatible bunch file.

In [132]:
from SDDS import writeSDDS

In [155]:
file_out = writeSDDS()

In [156]:
for i,(dim,unit) in enumerate(zip(('x','xp','y','yp','t','p'),('m','','m','','s', 'm$be$nc'))):
    file_out.create_column(dim, olive_back2_elegant[:,i], 'double',colUnits=unit)

In [157]:
file_out.save_sdds('write_out.sdds', dataMode='binary')